### ISSUE TITLE
Bug in Tantalus

### ISSUE THREAD

**Issue by TartarusTim** [thijsmie/tantalus#23]
hoi hoi,

Ik ben de zoveelste gebruiker van tantalus, laatst heb ik een bug ontdekt waarbij als ik een bepaalde transactie uit conscribo verwijder en deze transactie in tantalus aanpas deze niet meer wil syncen met conscribo.

dit is de feedback die tantalus terug geeft als ik het probeer te syncen:

Error voor thijs: Traceback (most recent call last): File "/app/ConscriboPyAPI/conscribo_sync.py", line 26, in sync_transactions conscribo.add_change_transaction(xml) File "/app/ConscriboPyAPI/conscribo_api.py", line 66, in add_change_transaction res = TransactionPutResult(tod.content, transaction) File "/app/ConscriboPyAPI/conscribo_mapper.py", line 199, in __init__ super(TransactionPutResult, self).__init__(data) File "/app/ConscriboPyAPI/conscribo_mapper.py", line 17, in __init__ tree = etree.fromstring(bytes(xml)) File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError File "<string>", line 6 lxml.etree.XMLSyntaxError: StartTag: invalid element name, line 6, column 2
--

**Comment by thijsmie** [comment]
Hoi Tim!

Hmm beetje jammer dat Conscribo niet een fatsoenlijke error teruggeeft (geen error code, geen messages, maar gewoon invalid data, tsk tsk). Eigenlijk denk ik dat de fout aan de Conscribo API kant ligt, maar dat kan ik niet zo makkelijk bewijzen. Zou je in conscribo een dummy boeking kunnen maken met de juiste referentie en kijken of het dan wel werkt?

**Comment by TartarusTim** [comment]
Hoi Thijs,

Zojuist een dummy boeking gemaakt, volgens mij deed deze het gewoon.

Op wo 15 dec. 2021 om 14:48 schreef Thijs Miedema ***@***.***
